services:
  web:
    image: nginx:stable
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/defult.conf
    depends_on:
      - bakend
  bakend:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: bakend
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQ_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASES_FASTFOOD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


